global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lammps-mcp-api'
    static_configs:
      - targets: ['api:18000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'lammps-mcp-redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'lammps-mcp-worker'
    static_configs:
      - targets: ['worker:18000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s